import HomeNavbar from "../components/HomeNavbar";
import HomeFooter from "../components/HomeFooter";
import { FileText } from "lucide-react";

const Terms = () => {
  const sections = [
    {
      title: "Acceptance of Terms",
      content: "By accessing and using Interview Buddy, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by these terms, please do not use this service."
    },
    {
      title: "Use of Service",
      content: "Interview Buddy is provided for personal, educational interview preparation purposes only. You agree not to use the service for any unlawful purpose, to impersonate others, or to interfere with the proper functioning of the platform."
    },
    {
      title: "User Accounts",
      content: "You are responsible for maintaining the confidentiality of your account credentials. You agree to notify us immediately of any unauthorized use of your account. We reserve the right to terminate accounts that violate these terms."
    },
    {
      title: "AI-Generated Content",
      content: "The questions, feedback, and content generated by our AI system are for educational purposes only. We do not guarantee the accuracy or completeness of AI-generated content. Always verify important information from authoritative sources."
    },
    {
      title: "Intellectual Property",
      content: "The Interview Buddy platform, including its design, features, and content, is owned by Interview Buddy and protected by copyright laws. You may not reproduce, distribute, or create derivative works without explicit permission."
    },
    {
      title: "Uploaded Content",
      content: "When you upload content (resumes, avatars), you grant Interview Buddy a non-exclusive license to use that content to provide our services. You retain ownership of your uploaded content and may delete it at any time."
    },
    {
      title: "Limitation of Liability",
      content: "Interview Buddy is provided 'as is' without warranties of any kind. We are not liable for any damages arising from your use of the service, including but not limited to loss of data, employment opportunities, or any other consequential damages."
    },
    {
      title: "Changes to Terms",
      content: "We reserve the right to modify these terms at any time. We will notify users of significant changes via email or platform notifications. Continued use of the service after changes constitutes acceptance of the new terms."
    },
    {
      title: "Contact",
      content: "For questions about these Terms of Service, please contact us at support@interviewbuddy.com."
    },
  ];

  return (
    <div className="min-h-screen flex flex-col bg-gray-50">
      <HomeNavbar />

      {/* Hero */}
      <div className="bg-gradient-to-br from-[#162447] via-[#2d5878] to-[#2fa6a2] text-white py-16 px-4">
        <div className="max-w-4xl mx-auto text-center">
          <div className="w-16 h-16 bg-white/20 rounded-full flex items-center justify-center mx-auto mb-4">
            <FileText size={32} className="text-white" />
          </div>
          <h1 className="text-3xl sm:text-5xl font-extrabold mb-4">Terms of Service</h1>
          <p className="text-white/80 text-sm">Last updated: May 2026</p>
        </div>
      </div>

      <div className="max-w-3xl mx-auto px-4 py-12 w-full">
        <div className="bg-white rounded-2xl shadow p-6 sm:p-8 space-y-6">
          <p className="text-gray-600 text-sm leading-relaxed border-l-4 border-[#243A6F] pl-4">
            Please read these Terms of Service carefully before using Interview Buddy.
            These terms govern your use of our platform and services.
          </p>

          {sections.map((section, i) => (
            <div key={i}>
              <h2 className="font-bold text-lg text-[#243A6F] mb-2 flex items-center gap-2">
                <span className="w-6 h-6 bg-blue-50 text-blue-600 rounded-full flex items-center justify-center text-xs font-bold shrink-0">
                  {i + 1}
                </span>
                {section.title}
              </h2>
              <p className="text-gray-600 text-sm leading-relaxed pl-8">{section.content}</p>
              {i < sections.length - 1 && <hr className="mt-6 border-gray-100" />}
            </div>
          ))}
        </div>
      </div>

      <HomeFooter />
    </div>
  );
};

export default Terms;